
package src.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionEtudiantWsService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8585/GestionEtudiant?wsdl")
public class GestionEtudiantWsService
    extends Service
{

    private final static URL GESTIONETUDIANTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONETUDIANTWSSERVICE_EXCEPTION;
    private final static QName GESTIONETUDIANTWSSERVICE_QNAME = new QName("http://service/", "GestionEtudiantWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8585/GestionEtudiant?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONETUDIANTWSSERVICE_WSDL_LOCATION = url;
        GESTIONETUDIANTWSSERVICE_EXCEPTION = e;
    }

    public GestionEtudiantWsService() {
        super(__getWsdlLocation(), GESTIONETUDIANTWSSERVICE_QNAME);
    }

    public GestionEtudiantWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONETUDIANTWSSERVICE_QNAME, features);
    }

    public GestionEtudiantWsService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONETUDIANTWSSERVICE_QNAME);
    }

    public GestionEtudiantWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONETUDIANTWSSERVICE_QNAME, features);
    }

    public GestionEtudiantWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionEtudiantWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GestionEtudiantWs
     */
    @WebEndpoint(name = "GestionEtudiantWsPort")
    public GestionEtudiantWs getGestionEtudiantWsPort() {
        return super.getPort(new QName("http://service/", "GestionEtudiantWsPort"), GestionEtudiantWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionEtudiantWs
     */
    @WebEndpoint(name = "GestionEtudiantWsPort")
    public GestionEtudiantWs getGestionEtudiantWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "GestionEtudiantWsPort"), GestionEtudiantWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONETUDIANTWSSERVICE_EXCEPTION!= null) {
            throw GESTIONETUDIANTWSSERVICE_EXCEPTION;
        }
        return GESTIONETUDIANTWSSERVICE_WSDL_LOCATION;
    }

}
